study_id: CUR-DEM-001
title: A randomized, double-blind, placebo-controlled study of Drug X in Hypertension
mechanism_class: ANTIHYPERTENSIVE
investigational_product_aliases: ["DRUG X", "INV_PRODUCT", "TEST ARTICLE"]

visit_schedule:
  - visit: Screening
    window: {min: "-P14D", max: "P0D"}
  - visit: Day 1
    window: {min: "P0D", max: "P1D"}
  - visit: Week 1
    window: {min: "P7D", max: "P9D"}

safety_monitoring:
  vitals_required: ["SYSBP", "DIABP", "HR"]
  labs_required: ["CREAT", "ALT", "AST"]

timing_windows:
  exposure_followup_vs: {min: "PT48H", max: "PT72H"}
