forms:
  - name: DEMOGRAPHICS
    domain: DM
    fields:
      - {name: USUBJID, type: string, required: true}
      - {name: AGE, type: integer, required: true, range: [18, 99]}
      - {name: SEX, type: enum, enum: [M, F], required: true}

  - name: VITALS
    domain: VS
    fields:
      - {name: USUBJID, type: string, required: true}
      - {name: VSTESTCD, type: enum, enum: [SYSBP, DIABP, HR], required: true}
      - {name: VSORRES, type: number, required: true}
      - {name: VSDTC, type: datetime, required: true}

  - name: ADVERSE EVENTS
    domain: AE
    fields:
      - {name: USUBJID, type: string, required: true}
      - {name: AEDECOD, type: string, required: true}
      - {name: AEGR, type: integer, required: false}
      - {name: AESTDTC, type: datetime, required: true}

  - name: EXPOSURE
    domain: EX
    fields:
      - {name: USUBJID, type: string, required: true}
      - {name: EXTRT, type: string, required: true}
      - {name: EXDOSE, type: number, required: false}
      - {name: EXDTC, type: datetime, required: true}
