study_id: CUR-DEM-001
domains:
  VS:
    semantic:
      - id: VS_SYS_RANGE_GENERIC
        when: VSTESTCD == "SYSBP"
        check: 80 <= VSORRES <= 200
        severity: MAJOR
        message: SYSBP outside generic plausible limits
        exceptions:
          mechanism_class: ANTIHYPERTENSIVE
          direction: LOW
      - id: VS_DIA_RANGE_GENERIC
        when: VSTESTCD == "DIABP"
        check: 50 <= VSORRES <= 120
        severity: MAJOR
        message: DIABP outside generic plausible limits
        exceptions:
          mechanism_class: ANTIHYPERTENSIVE
          direction: LOW
  AE:
    cross_domain:
      - id: AE_GENERIC_CORROBORATION
        severity: MAJOR
        message: AE lacks corroborating measurement in window
        params: {map_csv: ae_corroboration_map.csv}

temporal:
  - id: EX_REQUIRED_VS_WINDOWS
    severity: MINOR
    logic: Require VS on dose day and within +48–72h after any exposure
    params:
      vs_same_day: true
      followup_window: {min: "PT48H", max: "PT72H"}
